// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"LeAutoPushNPC","status":true,"description":"Replicates a feature on Seiken Densetsu 3 that allow the player\r\nto pushs NPC when they obstruct a way.","parameters":{"Push Delay":"50","Change Image ?":"false"}},
{"name":"SmartPath","status":true,"description":"Allows events or players to do smart Pathfinding","parameters":{}},
{"name":"Gamefocus","status":true,"description":"Pauses the Audio and/or Video when the game loses focus. Has callbacks for onPause, whilePaused, and onResume.","parameters":{"Pause Audio":"true","Pause Graphics":"true"}},
{"name":"SOUL_MV Turn and Move","status":true,"description":"v1.0 Makes the character turn to the direction before actual movement is executed.","parameters":{"Delay Time":"6"}},
{"name":"OrangeHud","status":true,"description":"OrangeHud 2.0 - Creates a custom HUD based on the params","parameters":{"DefaultFontFace":"Verdana","DefaultFontSize":"18","DefaultFontColor":"#FFFFFF","DefaultFontItalic":"false","HudWidth":"0","HudHeight":"0","HudX":"0","HudY":"0","HudOpacity":"0","SwitchId":"0","WindowMargin":"4","WindowPadding":"18","ShowOnMap":"true","ShowOnBattle":"false","ShowOnMenu":"false","ShowOnTitle":"false","ShowUnderTintLayer":"false","AutoRefresh":"true"}},
{"name":"OrangeHudLineGroup","status":true,"description":"Adds Several new Variables to Orange Hud","parameters":{"GroupName":"main","DefaultPattern":"%1","VariableList":"11,12,13,14","SwitchId":"10","X":"","Y":"","FontFace":"","FontSize":"","FontColor":"","FontItalic":"","LineHeight":"24","LineWidth":"0","UseScriptPattern":"false","PatternLine1":"\\i[210] %1","PatternLine2":"\\i[266] %1","PatternLine3":"\\i[7] %1","PatternLine4":"\\i[82] %1","PatternLine5":"","PatternLine6":"","PatternLine7":"","PatternLine8":"","PatternLine9":"","PatternLine10":""}},
{"name":"HIME_SelfVariables","status":true,"description":"v1.4 - Allows you to create and manage self-variables for all\r\nof your events!","parameters":{}},
{"name":"YEP_MessageCore","status":true,"description":"Adds more features to the Message Window to customized the\nway your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward":"Input.isPressed('pagedown')","Word Wrapping":"false","---Font---":"","Font Name":"GameFont","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]"}},
{"name":"HIME_MoveRouteCommands","status":true,"description":"v1.0 - Allows you to have a character move towards a specific\r\nevent","parameters":{}},
{"name":"YEP_SaveEventLocations","status":true,"description":"v1.04 Enable specified maps to memorize the locations of\nevents when leaving and loading them upon reentering map.","parameters":{}}
];
